import { canonicalizeReplayFixturePayload } from './replayCanonicalization';

const RAW_REPLAY_PARITY_FIXTURES = [
  {
    name: 'baseline-smoke',
    purpose: 'Balanced baseline fixture for deterministic replay smoke coverage.',
    seed: 'fixture-baseline-smoke',
    worldWidth: 800,
    worldHeight: 480,
    initialPopulation: 24,
    minimumPopulation: 12,
    initialFoodCount: 35,
    foodSpawnChance: 0.05,
    foodEnergyValue: 6,
    maxFood: 140,
    mutationRate: 0.08,
    mutationStrength: 0.12,
    tickBudget: 120
  },
  {
    name: 'high-food-low-mutation',
    purpose: 'Stress abundant-food dynamics with conservative mutation pressure.',
    seed: 'fixture-high-food-low-mutation',
    worldWidth: 920,
    worldHeight: 520,
    initialPopulation: 30,
    minimumPopulation: 16,
    initialFoodCount: 48,
    foodSpawnChance: 0.08,
    foodEnergyValue: 7,
    maxFood: 180,
    mutationRate: 0.03,
    mutationStrength: 0.06,
    tickBudget: 140
  },
  {
    name: 'tight-world-high-mutation',
    purpose: 'Exercise dense-world collision pressure with aggressive mutation variance.',
    seed: 'fixture-tight-world-high-mutation',
    worldWidth: 640,
    worldHeight: 360,
    initialPopulation: 20,
    minimumPopulation: 10,
    initialFoodCount: 24,
    foodSpawnChance: 0.03,
    foodEnergyValue: 5,
    maxFood: 110,
    mutationRate: 0.12,
    mutationStrength: 0.18,
    tickBudget: 130
  },
  {
    name: 'high-mutation-reproduction-churn',
    purpose: 'Stress deterministic replay under elevated mutation pressure and rapid reproduction-friendly food abundance.',
    seed: 'fixture-high-mutation-reproduction-churn',
    worldWidth: 760,
    worldHeight: 420,
    initialPopulation: 36,
    minimumPopulation: 18,
    initialFoodCount: 80,
    foodSpawnChance: 0.11,
    foodEnergyValue: 8,
    maxFood: 220,
    mutationRate: 0.2,
    mutationStrength: 0.24,
    tickBudget: 100
  },
  {
    name: 'minimum-population-recovery',
    purpose: 'Force deterministic minimum-population floor recovery under starvation pressure and verify canonical timeline parity.',
    seed: 'fixture-minimum-population-recovery',
    worldWidth: 700,
    worldHeight: 420,
    initialPopulation: 8,
    minimumPopulation: 14,
    initialFoodCount: 0,
    foodSpawnChance: 0,
    foodEnergyValue: 5,
    maxFood: 0,
    mutationRate: 0.1,
    mutationStrength: 0.14,
    tickBudget: 90
  },
  {
    name: 'cross-session-resume-drift',
    purpose: 'Validate deterministic parity before and after persisted save/resume across a two-phase replay path.',
    seed: 'fixture-cross-session-resume-drift',
    worldWidth: 840,
    worldHeight: 500,
    initialPopulation: 28,
    minimumPopulation: 14,
    initialFoodCount: 42,
    foodSpawnChance: 0.06,
    foodEnergyValue: 7,
    maxFood: 165,
    mutationRate: 0.1,
    mutationStrength: 0.16,
    tickBudget: 150,
    saveTick: 70,
    resumeTickBudget: 80
  },
  {
    name: 'long-horizon-parity-checkpoints',
    purpose: 'Catch deterministic replay drift that emerges after extended mutation/reproduction cycles using early/mid/late checkpoint parity.',
    seed: 'fixture-long-horizon-parity-checkpoints',
    worldWidth: 640,
    worldHeight: 360,
    initialPopulation: 10,
    minimumPopulation: 5,
    initialFoodCount: 12,
    foodSpawnChance: 0.02,
    foodEnergyValue: 6,
    maxFood: 36,
    mutationRate: 0.1,
    mutationStrength: 0.15,
    tickBudget: 360,
    checkpointTicks: [120, 240, 360]
  },
  {
    name: 'chunked-tick-execution-equivalence',
    purpose: 'Prove deterministic replay parity between continuous execution and segmented stop/resume cadence boundaries.',
    seed: 'fixture-chunked-tick-execution-equivalence',
    worldWidth: 760,
    worldHeight: 420,
    initialPopulation: 22,
    minimumPopulation: 12,
    initialFoodCount: 32,
    foodSpawnChance: 0.045,
    foodEnergyValue: 6,
    maxFood: 130,
    mutationRate: 0.09,
    mutationStrength: 0.13,
    tickBudget: 180,
    checkpointTicks: [90, 180],
    cadencePlans: [
      { id: 'continuous', segments: [180] },
      { id: 'segmented-resume', segments: [37, 41, 29, 73] }
    ]
  }
];

export const REPLAY_PARITY_FIXTURES = RAW_REPLAY_PARITY_FIXTURES.map((fixture) => canonicalizeReplayFixturePayload(fixture));
